### ISSUE TITLE
Bug in extensions.py that is preventing cron from running

### ISSUE THREAD

**Issue by Michaelcraun** [mietechnologies/MIE-MCServer#85]
Traceback (most recent call last):
  File "/home/bachapin/MIE-MCServer/main.py", line 20, in <module>
    from util.backup import Backup
  File "/home/bachapin/MIE-MCServer/util/backup.py", line 4, in <module>
    from .configuration import Maintenance
  File "/home/bachapin/MIE-MCServer/util/configuration.py", line 1, in <module>
    from .mielib import custominput as ci
  File "/home/bachapin/MIE-MCServer/util/mielib/custominput.py", line 5, in <module>
    from util.cron import CronDate, CronFrequency
  File "/home/bachapin/MIE-MCServer/util/cron.py", line 3, in <module>
    from util.date import Date
  File "/home/bachapin/MIE-MCServer/util/date.py", line 2, in <module>
    from .extension import string_contains, stringContainsAnyCase
  File "/home/bachapin/MIE-MCServer/util/extension.py", line 3, in <module>
    def cleanString(haystack: str, needles: list[str]) -> str:
TypeError: 'type' object is not subscriptable

**Comment by Michaelcraun** [comment]
So, from my investigations, it looks like this issue was two-fold. For one, `list[str]` is not the correct syntax (`List[str]` is). Additionally, there are some of the pip packages that use sudo commands in this project (such as CronTab, Discord, and RCON). Because these use sudo commands, they apparently have to be installed with a sudo install. We should probably take this into consideration during package installation with pipreqs.
